### ISSUE TITLE
Reference API docs problems in Standardese

### ISSUE THREAD

**Issue by ned14** [ned14/outcome#75]
Links to issues in foonathan/standardese
- [x]  Cannot suppress items from output foonathan/standardese#74
- [x] --input.blacklist_namespace=detail not entirely hiding namespace detail foonathan/standardese#94
- [ ] Support for Concepts TS (not merely documented concepts) foonathan/standardese#58
- [ ] Variable templates are not parsed correctly foonathan/standardese#76
- [ ] \param for macros do not appear foonathan/standardese#86
- [ ] Markdown generated is now misparsed by some renderers foonathan/standardese#98
- [ ] Function group names ought to be scoped local to the class owning them foonathan/standardese#103
- [ ] Output sections not appearing in outcome class synopsis foonathan/standardese#104
- [ ] Indent on extra lines in a list cause contents of the list to get mangled foonathan/standardese#105
- [ ] \verbatim isn't always being expanded foonathan/standardese#106
- [ ] Inheritance from excluded base class isn't reliable foonathan/standardese#107
- [ ] Inherited member functions having their class in their parameter list should show the inheriting class instead of 'hidden' foonathan/standardese#108

**Comment by foonathan** [comment]
Points 1 and 4 are now done.

**Comment by ned14** [comment]
Now ticked. I've invited you as collaborator so you can tick them yourself or edit stuff here in future.

**Comment by foonathan** [comment]
Thanks.

**Comment by ned14** [comment]
Closing as reference API documentation has been completely manually rewritten by hand. Thanks to @foonathan for his great tool, I am still using it in other projects.
